export const ECUADOR_DAILY_BASE_HOURS = 8;
export const ECUADOR_WEEKLY_BASE_HOURS = 40;
export const DEFAULT_ATTENDANCE_GRACE_MINUTES = 10;
export const MONTHLY_HOURLY_DIVISOR = 240;
export const SUPPLEMENTARY_PAY_MULTIPLIER = 1.5;
export const EXTRAORDINARY_PAY_MULTIPLIER = 2;
export const SUPPLEMENTARY_SURCHARGE_MULTIPLIER = 0.5;
export const EXTRAORDINARY_SURCHARGE_MULTIPLIER = 1;
